- name: Ensure required packages are installed
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ yum_packages }}"

#- name: upgrade all packages
#  yum:
#    name: '*'
#    state: latest

# Example removing a repository and cleaning up metadata cache
- name: Remove repository (and clean up left-over metadata)
  yum_repository:
    name: epel.repo
    state: absent
  notify: yum-clean-metadata

- name: DownLoad OKD 3.9 playbooks from https://github.com/openshift/openshift-ansible
  git:
    repo: 'https://github.com/felix-centenera/openshift-ansible.git'
    dest: release-3.9
    version: release-3.9
    clone: yes
    update: no
